news-admin/src/main/java/com/epam/news/admin/security/domain/UserDetailsImpl.java
package com.epam.news.admin.security.domain;

import com.epam.news.common.domain.Role;
import com.epam.news.common.domain.User;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


public final class UserDetailsImpl implements UserDetails {

    private User user;
    private Role role;


    public UserDetailsImpl(User userData, Role userRole) {
        user = userData;
        role = userRole;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        List<GrantedAuthority> authorities = new ArrayList<>();
        authorities.add(role::getRoleName);
        return authorities;
    }

    @Override
    public String getPassword() {
        return user.getPassword();
    }

    @Override
    public String getUsername() {
        return user.getLogin();
    }

    public User getUser() {
        return user;
    }

    public Role getRole() {
        return role;
    }

    public String getFullName() {
        return user.getUserName();
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}

news-admin/src/main/webapp/WEB-INF/views/template/css-list.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<spring:url value="/resources/css/main.css" var="mainCSS"/>
<spring:url value="https://fonts.googleapis.com/css?family=Oswald:400,300" var="mainFont"/>
<spring:url value="https://fonts.googleapis.com/icon?family=Material+Icons" var="icons"/>
<spring:url value="/resources/css/dropdown.css" var="dropdownCss"/>

<link href="${mainFont}" rel="stylesheet" type="text/css">
<link href="${icons}" rel="stylesheet">
<link href="${mainCSS}" rel="stylesheet">
<link href="${dropdownCss}" rel="stylesheet">

news-admin/src/main/webapp/WEB-INF/views/template/footer.jsp
<p>2016 EPAM Systems, Inc. All Rights Reserved.</p>

news-admin/src/main/webapp/WEB-INF/views/template/header.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<div>
    <c:url value="/news" var="newsLink"/>
    <a href="${newsLink}" class="logo"><i class="material-icons">import_contacts</i>NEWS PORTAL</a>


    <security:authorize access="isAuthenticated()">
        <c:url var="logoutUrl" value="/j_spring_security_logout"/>
        <div class="logout-holder">
            <form action="${logoutUrl}" method="post">
                <button class="button small logout">LOGOUT</button>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
            </form>
        </div>
        <div class="username-holder">
                ${fn:toUpperCase(pageContext.request.userPrincipal.principal.fullName)}
        </div>
    </security:authorize>

</div>

news-admin/src/main/webapp/WEB-INF/views/template/js-list.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<spring:url value="/resources/js/main.js" var="mainJS"/>
<spring:url value="http://code.jquery.com/jquery-latest.min.js" var="jQuery"/>
<spring:url value="/resources/js/management-tools.js" var="managementTools"/>
<spring:url value="/resources/js/multiple-delete.js" var="multipleDelete"/>
<spring:url value="/resources/js/pagination-utils.js" var="paginationUtils"/>
<spring:url value="/resources/js/multiple-dropdown.js" var="multipleDropdown"/>

<script src="${jQuery}" type="text/javascript"></script>
<script src="${mainJS}" type="text/javascript"></script>
<script src="${managementTools}" type="text/javascript"></script>
<script src="${multipleDelete}" type="text/javascript"></script>
<script src="${paginationUtils}" type="text/javascript"></script>
<script src="${multipleDropdown}" type="text/javascript"></script>

news-admin/src/main/webapp/WEB-INF/views/template/layout.jsp
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>
        <tiles:insertAttribute name="title"/>
    </title>

    <tiles:insertAttribute name="cssList"/>

</head>

<body>

<spring:htmlEscape defaultHtmlEscape="true" />

<header class="sticky">
    <tiles:insertAttribute name="header"/>
</header>

<menu>
    <tiles:insertAttribute name="menu"/>
</menu>

<main>
    <tiles:insertAttribute name="body"/>
</main>

<footer>
    <tiles:insertAttribute name="footer"/>
</footer>

<tiles:insertAttribute name="jsList"/>

</body>
</html>

news-admin/src/main/webapp/WEB-INF/views/template/login-layout.jsp
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>
        <tiles:insertAttribute name="title"/>
    </title>

    <tiles:insertAttribute name="cssList"/>

</head>

<body class="login-page">

<header class="sticky">
    <tiles:insertAttribute name="header"/>
</header>

<tiles:insertAttribute name="body"/>

<footer>
    <tiles:insertAttribute name="footer"/>
</footer>

<tiles:insertAttribute name="jsList"/>

</body>
</html>

news-admin/src/main/webapp/WEB-INF/views/template/menu.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="section">
    <c:url value="/news" var="newsLink"/>
    <a href="${newsLink}" class="page-link"> <i class="material-icons">view_headline</i> NEWS LIST </a>
</div>

<div class="section">
    <c:url value="/newsManagement" var="managementLink"/>
    <a href="${managementLink}" class="page-link"> <i class="material-icons">add</i> ADD NEWS </a>
</div>

<div class="section">
    <c:url value="/authors" var="authorsLink"/>
    <a href="${authorsLink}" class="page-link"> <i class="material-icons">perm_identity</i> AUTHORS </a>
</div>

<div class="section">
    <c:url value="/tags" var="tagsLink"/>
    <a href="${tagsLink}" class="page-link"> <i class="material-icons">grade</i> TAGS </a>
</div>